// apps/app-www/src/components/BlocksContent.svelte
<script>
    import CodeSnippet from "./blocks/CodeSnippet.svelte";
import RichText from "./blocks/RichText.svelte";

    export let blocks = [];
</script>

{#each blocks as block}
    {#if block.blockType === 'richText'}
        {#each block.richText as element}
            <RichText element={element} />
        {/each}
    {/if}

    {#if block.blockType === 'codeSnippet'}
        <CodeSnippet element={block} />
    {/if}
{/each}

// apps/app-www/src/components/BlocksContent.tsx
import { RichTextBlock } from "./blocks/RichText";
import CodeSnippetBlock from "./blocks/CodeSnippet";

interface BlocksContentProps {
    blocks: any[]
}

const BlocksContent = ({ blocks }: BlocksContentProps) => {


    return (
        <div>
            {blocks.map((block, i) => {
                switch (block.blockType) {
                    case "richText":
                        return (
                            <RichTextBlock key={i} elements={block.richText} />
                        );
                    case "codeSnippet":
                        return (
                            <CodeSnippetBlock key={i} code={block.code} language={block.language} />
                        );
                }
            })}
        </div>
    )
}

export default BlocksContent;
